### ISSUE TITLE
carbonserver incomplete query result

### ISSUE THREAD

**Issue by mamoep** [go-graphite/go-carbon#188] opened 2017-07-12 11:13 UTC
I am using the following setup:

Grafana 4.4.1 -> carbonapi 0.8 -> go-carbon (carbonserver) 0.10.1

I ran into an issue where not all values are displayed on a dashboard with template variables. When switching to native graphite-web backend, everything works as expected.

To pinpoint the issue I manually queried the carbonapi with the different queries.
The idea of the data structure is `Switch.Blade.Port.counter`
Here all valid ports are queried. The results from switch "foo02-2" are missing:
`wget -O carbonapi_issue.csv "http://localhost:8081/render?target=aliasByNode(rls.{foo01-1,foo01-2,foo02-1,foo02-2}.{3,4,5,6,9}.{2,4,5,26,27,28,29}.bad_word, 1, 2, 3)&from=-6h&until=now&format=csv"`

This query uses a wildcard for ports, all results are displayed correctly:
`wget -O carbonapi_working.csv "http://localhost:8081/render?target=aliasByNode(rls.{foo01-1,foo01-2,foo02-1,foo02-2}.{3,4,5,6,9}.*.bad_word, 1, 2, 3)&from=-6h&until=now&format=csv"`

I attached the go-carbon log output for the queries.
[carbonserver_query_issue.log.txt](https://github.com/lomik/go-carbon/files/1141761/carbonserver_query_issue.log.txt)

**Comment by genuss** [comment] 2017-07-14 15:37
That's actually true. I'm seeing this behavior too.
As as a temporaty workaround it's possible to provide "custom all value" for template variable in grafana and set it to "*".

**Comment by genuss** [comment] 2017-07-21 16:37
Well it looks like an intended behaviour. Having seen the code I can finally understand what's going on here. As ``filepath.Glob`` doesn't support curly brackets carbonserver does that manually. This is done [here](https://github.com/lomik/go-carbon/blob/master/carbonserver/carbonserver.go#L533). As you can see there is a ``maxGlobs`` from config which limits maximum amount of globs which will be used to actually find metrics. In your example there will be 140 patterns got from expanding your glob. If you use default configuration parameter for ``max-globs`` (which is 100) than you will get incomplete results. That is why my workaround works: it reduces expanded glob list drastically.

The only thing for developers I could suggest is to print a log warning that results of findHandler may be incomplete if ``maxGlobs`` is reached.

**Comment by mamoep** [comment] 2017-07-25 07:06
Thank you @genuss, that last comment shows the right direction. If I increase the max-globs value the query works as expected. 
I don't fully understand what a glob is and what the max-globs setting does to memory consumption. We have some dashboards that rely heavily on template variables and will have globs in the thousands.

**Comment by genuss** [comment] 2017-07-25 10:50
Well I increased ``max-globs`` to 10000 and don't see any considerable memory consumption increase. If I understand correctly memory consumption will be increased in peaks during request processing, so if you grafana server is not very highloaded (which is the case for me) you can safely increase this value.

**Closed as completed** 2017-07-25 11:28 UTC

**Comment by Civil** [comment] 2017-07-25 11:54
> The only thing for developers I could suggest is to print a log warning that results of findHandler may be incomplete if maxGlobs is reached.

I'll do that next time I'll send patches to carbonserver. Thanks for suggestion.

I also might bump defaults to 1000 or 10000 and write a better documentation on how it affects carbonserver.
